server:
  port:8080

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.entity

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/department?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
      content-type: text/html
